### ISSUE TITLE
Error in pom.xml

### ISSUE THREAD

**Issue by Mengyboi** [diamond-rip/BowBooster#1]
Your Maid dependency doesn't work. Please try changing it to something else.

**Comment by Mengyboi** [comment]
![image](https://user-images.githubusercontent.com/85426783/165013274-cbdee870-733f-4447-a1fa-127c273a993f.png)

**Comment by GoodestEnglish** [comment]
Fixed in [latest version](https://github.com/diamond-rip/BowBooster/commit/965de8ec7524bdd37308912c8c70f45ef4e36ad5)
